name: "ci_demo"
on: push
# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node.js environment
        uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
      - run: pnpm install
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install
        run: pnpm install
      - name: Extract Repository Name
        id: extract_repo
        run: echo "REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV
      - name: Build
        env:
          BASE_PATH: ${{ env.REPO_NAME }}
        run: pnpm build
      - name: Display dist file
        run: ls -la && ls dist/
        
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # 上传 dist 文件夹
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v5
      #   with:
      #     target_branch: gh-pages
      #     build_dir: dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: pull
      #   run: echo pull && ls
      # - name: install
      #   run: echo install
      # - name: build
      #   run: echo build
      # - name: publish
      #   run: echo publish
